name: learn-github-actions
on: [pull_request]
jobs:
  check-install-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8.0'
      - run: yarn install
      - run: yarn run test