name: tests
on:
  - pull_request
  - push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8.0'
      - run: yarn install
      - run: yarn run test
      - run: yarn run lint

  docker-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t cool .